// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermaCore.Infrastructure.Persistence;

#nullable disable

namespace ThermaCore.Infrastructure.Persistence.Migrations.TenantDb
{
    [DbContext(typeof(ThermaCoreTenantContext))]
    [Migration("20260708111401_AlterCapillaryLengthMmToDecimal")]
    partial class AlterCapillaryLengthMmToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThermaCore.Domain.Entities.Common.AppDocument", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AppDocuments");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Common.ItemBarcode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BarcodeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ModuleType")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("WeightPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ItemBarcodes");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Common.SpecialCode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("CodeType", "EntityType", "Code")
                        .IsUnique();

                    b.ToTable("SpecialCode");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.Unit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AD",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1789),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adet"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "KG",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1833),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "GR",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1834),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "TON",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1836),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "LT",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1837),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Litre"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "MT",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1838),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metre"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CM",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1842),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetre"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "MM",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1844),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milimetre"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "KM",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1845),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilometre"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "M2",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1846),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metrekare"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "CM2",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1847),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetrekare"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "M3",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1849),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metreküp"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "MIC",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1850),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mikron"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "GR/M2",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1851),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram/Metrekare"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "KG/M2",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1852),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram/Metrekare"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "PK",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1854),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Paket"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "KL",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1855),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Koli"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "KUT",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1856),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kutu"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "TK",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1857),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Takım"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "TBK",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1858),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tabaka"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "CU",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1859),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çuval"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "BDN",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1860),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bidon"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "TNK",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1861),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Teneke"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "KOV",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1862),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kova"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "DZ",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1863),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Düzine"
                        },
                        new
                        {
                            Id = 26L,
                            Code = "DST",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1864),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Deste"
                        },
                        new
                        {
                            Id = 27L,
                            Code = "OHM",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1866),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ohm"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "KW",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1867),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilowatt"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "W",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1868),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watt"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "SN",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1869),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saniye"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "DK",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1870),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dakika"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "SA",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1871),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saat"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "GUN",
                            CreatedDate = new DateTime(2026, 7, 8, 14, 14, 0, 758, DateTimeKind.Local).AddTicks(1872),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gün"
                        });
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Management.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EffectiveBuyingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EffectiveSellingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TcmbBuyingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TcmbSellingRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Management.SystemParameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyBarcodePrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultOtvId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultPurchaseKdvId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultSalesKdvId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DefaultWastageRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SystemParameters", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Management.TaxRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TaxType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("TaxRates", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Boya", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DryingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("HeatResistance")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ShelfLifeMonths")
                        .HasColumnType("int");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("Boyas");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Emaye", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("Emayes", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.HeatingElement", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PowerWatt")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TubeDiameterMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Voltage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("HeatingElements", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.QualityStandard", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialGroup")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("QualityStandards");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.RotarySwitch", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CurrentAmper")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Voltage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("RotarySwitches");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Screw", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Diameter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("Screws", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.SheetMetal", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Density")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(7.85m);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("GroupCodeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("QualityStandardId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SurfaceTypeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("GroupCodeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("QualityStandardId");

                    b.HasIndex("SpecialCodeId");

                    b.HasIndex("SurfaceTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("SheetMetals");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.SurfaceType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SurfaceTypes");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Thermostat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CapillaryLengthMm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CurrentAmper")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("MinTemperature")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("Thermostats");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Boya", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Emaye", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.HeatingElement", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.RotarySwitch", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Screw", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.SheetMetal", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "GroupCode")
                        .WithMany()
                        .HasForeignKey("GroupCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThermaCore.Domain.Entities.Production.QualityStandard", "QualityStandard")
                        .WithMany()
                        .HasForeignKey("QualityStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThermaCore.Domain.Entities.Production.SurfaceType", "SurfaceType")
                        .WithMany()
                        .HasForeignKey("SurfaceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThermaCore.Domain.Entities.Definitions.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupCode");

                    b.Navigation("QualityStandard");

                    b.Navigation("SpecialCode");

                    b.Navigation("SurfaceType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Production.Thermostat", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SpecialCode");
                });
#pragma warning restore 612, 618
        }
    }
}
