// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermaCore.Infrastructure.Persistence;

#nullable disable

namespace ThermaCore.Infrastructure.Persistence.Migrations.TenantDb
{
    [DbContext(typeof(ThermaCoreTenantContext))]
    [Migration("20260625193711_AddNewUnitSeedData")]
    partial class AddNewUnitSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.ItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.ToTable("ItemCategories", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.Unit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AD",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3816),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adet"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "KG",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3834),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "GR",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3879),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "TON",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3880),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "LT",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3881),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Litre"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "MT",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3882),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metre"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CM",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3883),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetre"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "MM",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3884),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milimetre"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "KM",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3885),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilometre"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "M2",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3886),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metrekare"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "CM2",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3887),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetrekare"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "M3",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3888),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metreküp"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "MIC",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3889),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mikron"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "GR/M2",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3890),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram/Metrekare"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "KG/M2",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3891),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram/Metrekare"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "PK",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3892),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Paket"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "KL",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3893),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Koli"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "KUT",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3894),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kutu"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "TK",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3895),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Takım"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "TBK",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3896),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tabaka"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "CU",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3897),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çuval"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "BDN",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3898),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bidon"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "TNK",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3899),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Teneke"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "KOV",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3900),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kova"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "DZ",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3900),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Düzine"
                        },
                        new
                        {
                            Id = 26L,
                            Code = "DST",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3901),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Deste"
                        },
                        new
                        {
                            Id = 27L,
                            Code = "OHM",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3902),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ohm"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "KW",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3903),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilowatt"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "W",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3904),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watt"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "SN",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3905),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saniye"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "DK",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3906),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dakika"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "SA",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3907),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saat"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "GUN",
                            CreatedDate = new DateTime(2026, 6, 25, 22, 37, 10, 695, DateTimeKind.Local).AddTicks(3908),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gün"
                        });
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.ItemCategory", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Definitions.ItemCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
