// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermaCore.Infrastructure.Persistence;

#nullable disable

namespace ThermaCore.Infrastructure.Persistence.Migrations.TenantDb
{
    [DbContext(typeof(ThermaCoreTenantContext))]
    [Migration("20260625145228_AddUnitAndItemCategory")]
    partial class AddUnitAndItemCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.ItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.ToTable("ItemCategories", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.Unit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AD",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3114),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adet"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "KG",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3129),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "GR",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3130),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "LT",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3131),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Litre"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "MT",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3132),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metre"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CM",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3133),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetre"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "MM",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3134),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milimetre"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "PK",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3135),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Paket"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "KL",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3136),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Koli"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "TON",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3137),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "TK",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3138),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Takım"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "CU",
                            CreatedDate = new DateTime(2026, 6, 25, 17, 52, 27, 580, DateTimeKind.Local).AddTicks(3139),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çuval"
                        });
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.ItemCategory", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Definitions.ItemCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
