// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThermaCore.Infrastructure.Persistence;

#nullable disable

namespace ThermaCore.Infrastructure.Persistence.Migrations.TenantDb
{
    [DbContext(typeof(ThermaCoreTenantContext))]
    [Migration("20260628181728_AddTaxRatesToTenant")]
    partial class AddTaxRatesToTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.ItemCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.ToTable("ItemCategories", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.Unit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AD",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9579),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adet"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "KG",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9598),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "GR",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9599),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "TON",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9600),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "LT",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9601),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Litre"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "MT",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9602),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metre"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CM",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9603),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetre"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "MM",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9604),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milimetre"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "KM",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9605),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilometre"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "M2",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9606),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metrekare"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "CM2",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9607),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetrekare"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "M3",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9608),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metreküp"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "MIC",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9609),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mikron"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "GR/M2",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9610),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram/Metrekare"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "KG/M2",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9611),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram/Metrekare"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "PK",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9612),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Paket"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "KL",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9613),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Koli"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "KUT",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9614),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kutu"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "TK",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9615),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Takım"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "TBK",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9616),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tabaka"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "CU",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9617),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çuval"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "BDN",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9618),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bidon"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "TNK",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9619),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Teneke"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "KOV",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9620),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kova"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "DZ",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9675),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Düzine"
                        },
                        new
                        {
                            Id = 26L,
                            Code = "DST",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9676),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Deste"
                        },
                        new
                        {
                            Id = 27L,
                            Code = "OHM",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9677),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ohm"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "KW",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9678),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilowatt"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "W",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9680),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watt"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "SN",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9681),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saniye"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "DK",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9681),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dakika"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "SA",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9682),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saat"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "GUN",
                            CreatedDate = new DateTime(2026, 6, 28, 21, 17, 27, 513, DateTimeKind.Local).AddTicks(9683),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gün"
                        });
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Management.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EffectiveBuyingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EffectiveSellingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TcmbBuyingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TcmbSellingRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Management.TaxRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TaxType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("TaxRates", (string)null);
                });

            modelBuilder.Entity("ThermaCore.Domain.Entities.Definitions.ItemCategory", b =>
                {
                    b.HasOne("ThermaCore.Domain.Entities.Definitions.ItemCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
