<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WinBeyazEsya.Application\WinBeyazEsya.Application.csproj" />
    <ProjectReference Include="..\WinBeyazEsya.Domain\WinBeyazEsya.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="System.Management" Version="10.0.9" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\MasterDb\" />
    <Folder Include="Persistence\Migrations\TenantDb\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

