// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinBeyazEsya.Infrastructure.Persistence;

#nullable disable

namespace WinBeyazEsya.Infrastructure.Persistence.Migrations.TenantDb
{
    [DbContext(typeof(WinBeyazEsyaTenantContext))]
    [Migration("20260811184815_UpdateBarcodeValueUniqueIndex")]
    partial class UpdateBarcodeValueUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Common.AppDocument", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AppDocuments");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Common.ItemBarcode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("BarcodeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ModuleType")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("WeightPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ItemBarcodes");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Common.SpecialCode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("CodeType", "EntityType", "Code")
                        .IsUnique();

                    b.ToTable("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.ChemicalAndInsulationGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.HasIndex("Code", "BranchId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("ChemicalAndInsulationGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.ElectricalElectronicGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("ElectricalElectronicGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.FinishedGood", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GroupType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesVatRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.HasIndex("UnitId");

                    b.ToTable("FinishedGoods", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.GasAndIgnitionGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("GasAndIgnitionGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.GeneralExpense", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("GeneralExpenses", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.MechanicalAndHardwareGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("MechanicalAndHardwareGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.MetalSheetGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Density")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QualityCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.Property<int>("SurfaceCoatingType")
                        .HasColumnType("int");

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("MetalSheetGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.OtherMaterialGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("OtherMaterialGroups");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.PackagingAndPrintingGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.HasIndex("Code", "BranchId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PackagingAndPrintingGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.PlasticAndVisualPartsGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("PlasticAndVisualPartsGroups", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.Unit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AD",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9148),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Adet"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "KG",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9166),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "GR",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9167),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "TON",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9169),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "LT",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9170),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Litre"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "MT",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9170),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metre"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CM",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9171),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetre"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "MM",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9172),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Milimetre"
                        },
                        new
                        {
                            Id = 13L,
                            Code = "KM",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9180),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilometre"
                        },
                        new
                        {
                            Id = 14L,
                            Code = "M2",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9181),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metrekare"
                        },
                        new
                        {
                            Id = 15L,
                            Code = "CM2",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9182),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Santimetrekare"
                        },
                        new
                        {
                            Id = 16L,
                            Code = "M3",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9183),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Metreküp"
                        },
                        new
                        {
                            Id = 17L,
                            Code = "MIC",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9184),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mikron"
                        },
                        new
                        {
                            Id = 18L,
                            Code = "GR/M2",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9185),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gram/Metrekare"
                        },
                        new
                        {
                            Id = 19L,
                            Code = "KG/M2",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9186),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilogram/Metrekare"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "PK",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9186),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Paket"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "KL",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9187),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Koli"
                        },
                        new
                        {
                            Id = 20L,
                            Code = "KUT",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9188),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kutu"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "TK",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9189),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Takım"
                        },
                        new
                        {
                            Id = 21L,
                            Code = "TBK",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9190),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tabaka"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "CU",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9191),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çuval"
                        },
                        new
                        {
                            Id = 22L,
                            Code = "BDN",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9192),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bidon"
                        },
                        new
                        {
                            Id = 23L,
                            Code = "TNK",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9193),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Teneke"
                        },
                        new
                        {
                            Id = 24L,
                            Code = "KOV",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9194),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kova"
                        },
                        new
                        {
                            Id = 25L,
                            Code = "DZ",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9195),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Düzine"
                        },
                        new
                        {
                            Id = 26L,
                            Code = "DST",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9196),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Deste"
                        },
                        new
                        {
                            Id = 27L,
                            Code = "OHM",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9197),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ohm"
                        },
                        new
                        {
                            Id = 28L,
                            Code = "KW",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9198),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kilowatt"
                        },
                        new
                        {
                            Id = 29L,
                            Code = "W",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9199),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Watt"
                        },
                        new
                        {
                            Id = 30L,
                            Code = "SN",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9200),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saniye"
                        },
                        new
                        {
                            Id = 31L,
                            Code = "DK",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9201),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dakika"
                        },
                        new
                        {
                            Id = 32L,
                            Code = "SA",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9202),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Saat"
                        },
                        new
                        {
                            Id = 33L,
                            Code = "GUN",
                            CreatedDate = new DateTime(2026, 8, 11, 21, 48, 15, 320, DateTimeKind.Local).AddTicks(9203),
                            CreatedUserId = 1L,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Gün"
                        });
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.UnitConversion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Divisor")
                        .HasColumnType("decimal(18,5)");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainUnit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(18,5)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("UnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("EntityId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitConversions", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.WireAndGridGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("BaseUnitId")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoatingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("SpecialCodeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SpecialCodeId");

                    b.ToTable("WireAndGridGroups");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Management.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EffectiveBuyingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EffectiveSellingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TcmbBuyingRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TcmbSellingRate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Management.MaliyetParametre", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AverageProductionValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaturityDifferenceRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("WastageRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("CostParameters");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Management.SystemParameter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyBarcodePrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultOtvId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultPurchaseKdvId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultSalesKdvId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DefaultWastageRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SystemParameters", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Management.TaxRate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TaxType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("TaxRates", (string)null);
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Production.MaterialCost", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModifiedUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("MaterialCost");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.ChemicalAndInsulationGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.ElectricalElectronicGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.FinishedGood", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpecialCode");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.GasAndIgnitionGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.MechanicalAndHardwareGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.MetalSheetGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.OtherMaterialGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.PackagingAndPrintingGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.PlasticAndVisualPartsGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.UnitConversion", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("WinBeyazEsya.Domain.Entities.Definitions.WireAndGridGroup", b =>
                {
                    b.HasOne("WinBeyazEsya.Domain.Entities.Definitions.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WinBeyazEsya.Domain.Entities.Common.SpecialCode", "SpecialCode")
                        .WithMany()
                        .HasForeignKey("SpecialCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseUnit");

                    b.Navigation("SpecialCode");
                });
#pragma warning restore 612, 618
        }
    }
}
