<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WinBeyazEsya.Application\WinBeyazEsya.Application.csproj" />
    <ProjectReference Include="..\WinBeyazEsya.Infrastructure\WinBeyazEsya.Infrastructure.csproj" />
    <ProjectReference Include="..\WinBeyazEsya.Domain\WinBeyazEsya.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Win.Design" Version="25.2.6-pre-26075" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="tr\DevExpress.AIIntegration.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.AIIntegration.WinForms.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Blazor.PivotTable.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Blazor.Reporting.v25.2.Viewer.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Blazor.RichEdit.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Blazor.v25.2.Viewer.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Charts.Designer.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Dashboard.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Dashboard.v25.2.Web.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Dashboard.v25.2.Win.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Data.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.DataAccess.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.DataAccess.v25.2.UI.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Diagram.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Dialogs.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Drawing.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.EntityFrameworkCore.Security.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.AuditTrail.Xpo.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Chart.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.CloneObject.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Dashboards.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Dashboards.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Dashboards.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.FileAttachment.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.FileAttachment.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Notifications.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Notifications.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Office.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Office.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.PivotGrid.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.ReportsV2.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.ReportsV2.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.ReportsV2.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Scheduler.Blazor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Scheduler.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Scheduler.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Security.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Security.Xpo.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.StateMachine.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Validation.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Validation.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.ViewVariantsModule.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ExpressApp.Win.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Map.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Mvvm.v25.2.DataModel.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Office.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Pdf.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Persistent.Base.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Persistent.BaseImpl.EFCore.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Persistent.BaseImpl.Xpo.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.PivotGrid.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Printing.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.ReportServer.v25.2.Localization.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.RichEdit.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Snap.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Snap.v25.2.Extensions.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Snap.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Sparkline.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Spreadsheet.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Utils.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Utils.v25.2.UI.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxDiagram.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxGantt.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxHtmlEditor.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxRichEdit.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxScheduler.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxSpellChecker.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxSpreadsheet.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.ASPxTreeList.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.Resources.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Web.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Charts.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.CodeView.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Controls.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Core.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Docking.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.DocumentViewer.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Gantt.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Gauges.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Grid.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.LayoutControl.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.NavBar.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.PdfViewer.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Printing.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.PropertyGrid.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.ReportDesigner.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Ribbon.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.RichEdit.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Scheduler.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Scheduling.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.SpellChecker.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpf.Spreadsheet.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.Xpo.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraBars.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraCharts.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraCharts.v25.2.Wizard.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraEditors.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraGantt.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraGauges.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraGauges.v25.2.Presets.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraGrid.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraLayout.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraNavBar.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraPdfViewer.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraPivotGrid.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraPrinting.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraReports.v25.2.Extensions.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraReports.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraReports.v25.2.Web.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraRichEdit.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraScheduler.v25.2.Core.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraScheduler.v25.2.Extensions.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraScheduler.v25.2.Reporting.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraScheduler.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraSpellChecker.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraSpreadsheet.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraTreeList.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraVerticalGrid.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tr\DevExpress.XtraWizard.v25.2.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>$(AssemblyName)</Product>
  </PropertyGroup>

</Project>
